config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
 
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
 
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">

    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">

    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Show', @friend, class:"btn btn-dark" %> 

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
            <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
          </td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>
  <h1>Hello World!</h1>

<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> |
    <%= @friend.phone %> |
    <%= @friend.twitter %>
  </p>
  
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>	

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      	<%= link_to 'About Us', home_about_path, class:"nav-link" %>
      </li>
      
      
      

      <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
        
      <% end %>      

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Friends App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
        <br>

        <% if notice %>    
            <%= render 'layouts/alerts' %>  
        <% end %>

      <%= yield %>
      
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>